// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10
// terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued
// terms.

function fibonacciSumEven(limit, a = 1, b = 2, evenSum = 0) {
  if (b > limit) {
    return evenSum;
  }
  if (b % 2 === 0) {
    evenSum += b;
  }
  return fibonacciSumEven(limit, b, a + b, evenSum);
}
const limit = 4000000;

const result = fibonacciSumEven(limit);
console.log(result);
